goldmark:
    renderer:
        ## Set to true if you have HTML content inside Markdown
        unsafe: true
tableOfContents:
    startLevel: 0
    endLevel: 100
    ordered: true
highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
